### ISSUE TITLE
Parse error: syntax error, unexpected ':', expecting ';' or '{' in C:\boxuantech\dns-updater\alicloud-php-updaterecord\V20150109\AlicloudUpdateRecord.php on line 62

### ISSUE THREAD

**Issue by ethanleellj** [roura356a/alicloud-php-dns-updater#3]
Parse error: syntax error, unexpected ':', expecting ';' or '{' in C:\boxuantech\dns-updater\alicloud-php-updaterecord\V20150109\AlicloudUpdateRecord.php on line 62

**Comment by vc12345679** [comment]
It's a PHP compatibility issue. Code can only be run in PHP7 environment. We have to modify it to make it work under PHP5.6.

**Comment by rouralberto** [comment]
As @vc12345679 mentioned, the code is supposed to be executed in modern environments from 7+. Sorry for not mentioning it in the docs.
