### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by lordmen99** [roura356a/alicloud-php-dns-updater#4]
i try your code get this = 

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/tripjek99/public_html/alidns/alicloud-php-updaterecord/V20150109/AlicloudUpdateRecord.php on line 62

how fix it?

**Comment by rouralberto** [comment]
Sorry for the late reply, @lordmen99. The code is meant to run on PHP 7.0+. The error you are having is related with return types. Which version are you using?
