### ISSUE TITLE
Can support AAAA DNSR?

### ISSUE THREAD

**Issue by qNFCp** [roura356a/alicloud-php-dns-updater#5]
Is there any way to modify the AAAA DNSR of IPv6? 
有没有办法修改IPv6的AAAA解析呢?

**Comment by rouralberto** [comment]
Hi @qNFCp, did you tried the following code?
```
$updater->setDomainName('DOMAIN.COM');
$updater->setRecordType('AAAA');
$updater->setRR('@');
$updater->setValue('ff03:0:0:0:0:0:0:c1');
```

**Comment by qNFCp** [comment]
Hello @roura356a ,I tried to write it this way, but it would fail.
The partial return value is as follows:

Array ( [Recommend] => https://error-center.aliyun.com/status/search?Keyword=SignatureDoesNotMatch&source=PopGw [Message] => Specified signature is not matched with our calculation.

I checked my Access Key ID and Access Key Secret,They are correct.
Can you solve this issuess? Thanks!

**Comment by badgv** [comment]
> Hello @roura356a ,I tried to write it this way, but it would fail.
> The partial return value is as follows:
> 
> Array ( [Recommend] => https://error-center.aliyun.com/status/search?Keyword=SignatureDoesNotMatch&source=PopGw [Message] => Specified signature is not matched with our calculation.
> 
> I checked my Access Key ID and Access Key Secret,They are correct.
> Can you solve this issuess? Thanks!

修改alicloud-php-updaterecord/V20150109/AlicloudUpdateRecord.php的第206行
'Value' => $this->value,
修改为以下内容就能更新AAAA的IPV6地址了
'Value' => urlencode($this->value),

**Comment by qNFCp** [comment]
> > Hello @roura356a ,I tried to write it this way, but it would fail.
> > The partial return value is as follows:
> > Array ( [Recommend] => https://error-center.aliyun.com/status/search?Keyword=SignatureDoesNotMatch&source=PopGw [Message] => Specified signature is not matched with our calculation.
> > I checked my Access Key ID and Access Key Secret,They are correct.
> > Can you solve this issuess? Thanks!
> 
> 修改alicloud-php-updaterecord/V20150109/AlicloudUpdateRecord.php的第206行
> 'Value' => $this->value,
> 修改为以下内容就能更新AAAA的IPV6地址了
> 'Value' => urlencode($this->value),

成功了，谢谢啦

**Comment by rouralberto** [comment]
Thank you, @badgv. I'm glad it worked, @qNFCp =)
